# OpenTelemetry Configuration
# Add this to your main application.yml or use as a separate profile

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Trace everything (reduce in production)
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

otel:
  exporter:
    otlp:
      endpoint: http://otel-collector.observability.svc.cluster.local:4317
      protocol: grpc
  resource:
    attributes:
      service.name: neohoods-platform-api
      service.version: ${project.version:unknown}
      deployment.environment: ${SPRING_PROFILES_ACTIVE:development}

# Logging configuration with trace correlation
logging:
  pattern:
    level: "%5p [traceId=%X{trace_id:-}, spanId=%X{span_id:-}] %logger{36} - %msg%n"
  level:
    io.opentelemetry: DEBUG
    com.neohoods.portal: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
