management:
  tracing:
    enabled: true
    sampling:
      probability: 0.1 # Sample 10% of traces in production
  otlp:
    metrics:
      enabled: true
      url: http://tempo.observability.svc.cluster.local:4317/v1/metrics
    tracing:
      enabled: true
      url: http://tempo.observability.svc.cluster.local:4317/v1/traces
  metrics:
    export:
      otlp:
        enabled: true
        url: http://tempo.observability.svc.cluster.local:4317/v1/metrics
    tags:
      application: neohoods-platform-api
      version: ${project.version:unknown}
      environment: ${SPRING_PROFILES_ACTIVE:production}

# Production logging configuration
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    io.micrometer.registry.otlp: INFO
  pattern:
    level: "%5p [traceId=%X{trace_id:-}, spanId=%X{span_id:-}] %logger{36} - %msg%n"
